Feature/add manual listen
btcven/locha-mesh-chat pull request #119
Opened 2020-09-21 13:29 UTC by xkevin190

A new functionality was added in the administration panel, you can add the chat service listening addresses, once modified, it will always start in the address that the user has chosen

There are two options, one of type `defafult` to listen in all available directions and the other to select that the server listen in only one direction.

2020-09-21 13:34 UTC, jeandudey commented on src/views/config/AddNewAddressListen.js
> +            por favor seleccion un address donde desea escuchar
```suggestion
            por favor selecciona un address donde desea escuchar
```

2020-09-21 13:35 UTC, luisan00 requested changes

2020-09-21 13:35 UTC, luisan00 commented on android/app/src/main/java/DeviceInfo/DeviceInfoModule.java
> +
```suggestion
```

2020-09-21 13:35 UTC, luisan00 commented on android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
> +
```suggestion
```

2020-09-21 13:35 UTC, luisan00 commented on android/app/src/main/rust/src/runtime.rs
> +
```suggestion
```

2020-09-21 13:35 UTC, luisan00 commented on src/utils/chatService.js
> +
```suggestion
```

2020-09-21 13:35 UTC, luisan00 commented on src/views/config/AddNewAddressListen.js
> +
```suggestion
```

2020-09-21 13:35 UTC, luisan00 commented on android/app/src/main/java/DeviceInfo/Utils.java
> +
```suggestion
```

2020-09-21 13:35 UTC, luisan00 commented on android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
> +
```suggestion
```

2020-09-21 13:35 UTC, luisan00 commented on android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
> +
```suggestion
```

2020-09-21 13:35 UTC, luisan00 commented on android/app/src/main/rust/src/runtime.rs
> +
```suggestion
```

2020-09-21 13:35 UTC, luisan00 commented on android/app/src/main/rust/src/runtime.rs
> +
```suggestion
```

2020-09-21 13:35 UTC, luisan00 commented on src/store/configuration/congurationAction.js
> +
```suggestion
```

2020-09-21 17:33 UTC, jeandudey commented on android/app/src/main/java/io/locha/p2p/runtime/Runtime.java
> +                         boolean attemptUpnp, String address) throws RuntimeException {
s/address/listenAddress/

2020-09-21 17:33 UTC, jeandudey commented on android/app/src/main/java/io/locha/p2p/runtime/Runtime.java
> +    private native void nativeNew(byte[] privateKey, boolean attemptUpnp, String address);
s/address/listenAddress/

2020-09-21 17:34 UTC, jeandudey commented on android/app/src/main/java/io/locha/p2p/service/ChatService.java
> +    private static final String DEFAULT_ADDRESS_LISTEN = "/ip4/0.0.0.0/tcp/4444";
```suggestion
    private static final String DEFAULT_LISTEN_ADDRESS = "/ip4/0.0.0.0/tcp/4444";
```

2020-09-21 17:34 UTC, jeandudey commented on android/app/src/main/java/io/locha/p2p/service/ChatService.java
> +    private static final String DEFAULT_ADDRESS_LISTEN = "/ip4/0.0.0.0/tcp/4444";
This could be moved to Runtime.java, make the address parameter nullable and when null use this default address.

2020-09-21 18:00 UTC, jeandudey commented on android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
> +               return "/ip6/"+ip+"/tcp/4444";
```suggestion
               return String.format("/ip6/%s/tcp/4444", ip.toString());
```

2020-09-21 18:00 UTC, jeandudey commented on android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
> +               return "/ip4/"+ip+"/tcp/4444";
Same as previous

2020-09-21 18:01 UTC, jeandudey commented on android/app/src/main/rust/src/runtime.rs
> +        ?.into();
```suggestion
        let input: String = env.get_string(address)?.into();                                                               
```

2020-09-21 18:21 UTC, xkevin190 commented on android/app/src/main/java/io/locha/p2p/runtime/Runtime.java
> +                         boolean attemptUpnp, String address) throws RuntimeException {
i don't understand xD

2020-09-21 18:21 UTC, xkevin190 commented on android/app/src/main/java/io/locha/p2p/runtime/Runtime.java
> +    private native void nativeNew(byte[] privateKey, boolean attemptUpnp, String address);
i don't understand xD

2020-09-21 19:22 UTC, jeandudey commented on android/app/src/main/java/io/locha/p2p/runtime/Runtime.java
> +                         boolean attemptUpnp, String address) throws RuntimeException {
```suggestion
                         boolean attemptUpnp, String listenAddress) throws RuntimeException {
```

2020-09-21 19:23 UTC, jeandudey commented on android/app/src/main/java/io/locha/p2p/service/ChatServiceModule.java
> +            start(privKey,false, address, promise );
```suggestion
           // starting service again
           start(privKey,false, address, promise );
```

2020-09-21 19:38 UTC, jeandudey approved these changes

2020-09-22 09:34 UTC, luisan00 commented
Some need to be fixed before to proceed, build  is failing

2020-09-22 19:57 UTC, luisan00 approved these changes

2020-09-22 20:22 UTC, merged