Bugs/small errors
btcven/locha-mesh-chat pull request #136
Opened 2020-10-10 02:40 UTC by xkevin190

message bugs fixed:
- error handling when a plain message arrives
- validations that verify that the message is from a contact and that it is addressed to him
- Errors in status messages

2020-10-10 02:41 UTC, jeandudey approved these changes

2020-10-10 13:41 UTC, luisan00 requested changes

2020-10-10 13:41 UTC, luisan00 commented on __tests__/Views/configuration/AdministrativeComponent-test.js
> +
```suggestion
```

2020-10-10 13:41 UTC, luisan00 commented on __tests__/Views/configuration/AdministrativeComponent-test.js
> +
```suggestion
```

2020-10-10 13:41 UTC, luisan00 commented on __tests__/Views/configuration/AdministrativeComponent-test.js
> +  test('activate upnp', () => {
it's not very important in this point but the correct spelling is UPnP, which stands for **U**niversal **P**lug a**n**d **P**lay 
```suggestion
  test('activate UPnP', () => {
```

2020-10-10 13:41 UTC, luisan00 commented on __tests__/Views/configuration/AdministrativeComponent-test.js
> +  test('disable upnp', () => {
```suggestion
  test('disable UPnP', () => {
```

2020-10-13 03:14 UTC, luisan00 approved these changes

2020-10-13 15:40 UTC, merged