Feature/broadcast chat
btcven/locha-mesh-chat pull request #143
Opened 2020-10-20 21:08 UTC by xkevin190

the public chat channel was added again

2020-10-22 21:16 UTC, luisan00 requested changes
just a little change. without importance

2020-10-22 21:16 UTC, luisan00 commented on __tests__/Views/configuration/AdministrativeComponent-test.js
> +  test('disabled bradcast chat', () => {
```suggestion
  test('disabled broadcast chat', () => {
```

2020-10-22 21:17 UTC, xkevin190 commented on __tests__/Views/configuration/AdministrativeComponent-test.js
> +  test('disabled bradcast chat', () => {
ok

2020-10-26 15:08 UTC, jeandudey approved these changes

2020-10-26 15:09 UTC, luisan00 approved these changes
epale!

2020-10-26 15:09 UTC, merged