Feature/avoid dougle play
btcven/locha-mesh-chat pull request #153
Opened 2020-12-02 19:38 UTC by xkevin190

added the modification to pause the player if another message is played

2020-12-02 21:38 UTC, jeandudey approved these changes

2020-12-03 14:38 UTC, luisan00 requested changes

2020-12-03 14:38 UTC, luisan00 commented on __tests__/components/player-test.js
> +
Extra line 
```suggestion
```

2020-12-03 14:38 UTC, luisan00 commented on __tests__/components/player-test.js
> +
Extra line
```suggestion
```

2020-12-04 15:02 UTC, luisan00 approved these changes

2020-12-04 15:02 UTC, merged