notifications fixed
btcven/locha-mesh-chat pull request #165
Opened 2021-01-06 23:56 UTC by xkevin190

2021-01-07 11:26 UTC, jeandudey requested changes

2021-01-07 11:26 UTC, jeandudey commented on App.js
> +import NativationService from './src/utils/navigationService';
```suggestion
import NavigationService from './src/utils/navigationService';
```

:eyes:

2021-01-08 14:30 UTC, luisan00 approved these changes

2021-01-10 16:51 UTC, jeandudey approved these changes

2021-01-10 16:53 UTC, merged